name: Check Runtimes on Release edits

on:
  release:
    types: [edited]

env:
  RUNTIME_SPECS_DIR: .github/runtime_specs/

jobs:
  find-specs:
    name: Fetch the list of available runtime specs
    outputs:
      specs: ${{ steps.get-list.outputs.specs }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Get list
        id: get-list
        run: |
          lst=$(ls $RUNTIME_SPECS_DIR/*.json | xargs -I{} basename "{}" .json | tr '\n' ',' | sed 's/,$//')
          echo "Found: $lst"
          echo "specs=[$lst]" >> $GITHUB_OUTPUT

  check_runtimes:
    name: Fetch the list of available runtime specs
    runs-on: ubuntu-latest
    needs:
      - find-specs

    strategy:
      matrix:
        specs: ${{ fromJSON(needs.find-specs.outputs.specs) }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: .*\.wasm
          name_is_regexp: true
          allow_forks: false
          path: runtimes

      - name: Install tooling
        run: |
          echo "TODO"

      - name: Extract metadata JSON for ${{ matrix.specs }}
        env:
          RUNTIME: ${{ matrix.specs }}
        run: |
          echo "TODO: Get metadata for $RUNTIME"

      - name: Check specs for ${{ matrix.specs }}
        id: build
        env:
          RUNTIME: ${{ matrix.specs }}
        run: |
          echo "WIP"
          python --version
          python .github/scripts/check_runtime.py runtimes/$RUNTIME.json $RUNTIME_SPECS_DIR/$RUNTIME
