name: Check Runtimes Specs

on:
  workflow_dispatch:

  release:
    types: [edited]

env:
  RUNTIME_SPECS_DIR: .github/runtime_specs/
  DATA_DIR: runtimes

jobs:
  find-specs:
    name: Fetch the list of available runtime specs
    outputs:
      specs: ${{ steps.get-list.outputs.specs }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Get list
        id: get-list
        run: |
          lst=$(ls $RUNTIME_SPECS_DIR/*.json | xargs -I{} basename "{}" .json | jq -R .| jq -s .
          lst=$(echo "[$lst]")
          echo "Found: $lst"
          echo "specs=$lst" >> $GITHUB_OUTPUT

  check_runtimes:
    name: Fetch the list of available runtime specs
    runs-on: ubuntu-latest
    needs:
      - find-specs

    strategy:
      matrix:
        specs: ${{ fromJSON(needs.find-specs.outputs.specs) }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: .*\.wasm
          name_is_regexp: true
          allow_forks: false
          path: $DATA_DIR

      - name: Rust Cache
        uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1
        with:
          cache-on-failure: true

      - name: Install tooling
        run: |
          cargo install subwmasm
          subwasm --version

      - name: Extract metadata JSON for ${{ matrix.specs }}
        env:
          RUNTIME: ${{ matrix.specs }}
        run: |
          subwasm get --chain ${{ matrix.specs }} -o $DATA_DIR/$RUNTIME.wasm
          subwasm metadata --json $DATA_DIR/$RUNTIME.wasm | tee $DATA_DIR/$RUNTIME.json

      - name: Check specs for ${{ matrix.specs }}
        id: build
        env:
          RUNTIME: ${{ matrix.specs }}
        run: |
          echo "WIP"
          python --version
          python .github/scripts/check_runtime.py $DATA_DIR/$RUNTIME.json $RUNTIME_SPECS_DIR/$RUNTIME.json
